"""initial schema

Revision ID: 90d04f63fc49
Revises:
Create Date: 2026-05-18 01:37:42.250207

Captures the full v1.12 schema from Base.metadata. Database-agnostic:
all columns use SQLAlchemy generic types (Integer, String, JSON, Float,
DateTime(timezone=True), Date, Text, Boolean) which compile to the right
underlying type per dialect (e.g. JSON → JSONB on Postgres, TEXT on SQLite).

On Postgres this is the only migration that runs (`alembic upgrade head`).
On SQLite we don't run alembic at all — `migrations.py` adds new columns
in place. See `openscout/migrations.py` for the rationale.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90d04f63fc49"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_briefs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brief_date", sa.Date(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("issue", sa.Integer(), nullable=False),
        sa.Column("rendered_md", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("daily_briefs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_daily_briefs_brief_date"), ["brief_date"], unique=True)

    op.create_table(
        "deep_dive_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "enqueued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deep_dive_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deep_dive_jobs_slug"), ["slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_deep_dive_jobs_state"), ["state"], unique=False)

    op.create_table(
        "deep_dive_quota",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=False),
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column(
            "first_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deep_dive_quota", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deep_dive_quota_day"), ["day"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_deep_dive_quota_ip_address"), ["ip_address"], unique=False
        )

    op.create_table(
        "institutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_zh", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("prestige_score", sa.Float(), nullable=True),
        sa.Column("openalex_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("institutions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_institutions_name"), ["name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_institutions_openalex_id"), ["openalex_id"], unique=True
        )

    op.create_table(
        "papers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("arxiv_id", sa.String(length=32), nullable=True),
        sa.Column("semantic_scholar_id", sa.String(length=64), nullable=True),
        sa.Column("openalex_id", sa.String(length=64), nullable=True),
        sa.Column("doi", sa.String(length=128), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("abstract_zh", sa.Text(), nullable=True),
        sa.Column("one_liner_zh", sa.Text(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("venue", sa.String(length=128), nullable=True),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("code_url", sa.Text(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=False),
        sa.Column("influential_citation_count", sa.Integer(), nullable=True),
        sa.Column("github_stars", sa.Integer(), nullable=True),
        sa.Column("buzz_score", sa.Float(), nullable=True),
        sa.Column("breakthrough_score", sa.Float(), nullable=True),
        sa.Column("commercial_score", sa.Float(), nullable=True),
        sa.Column("work_score", sa.Float(), nullable=True),
        sa.Column("work_score_reasons", sa.JSON(), nullable=True),
        sa.Column("concepts", sa.JSON(), nullable=True),
        sa.Column("author_emails", sa.JSON(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("semantic_scholar_id"),
    )
    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_papers_arxiv_id"), ["arxiv_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_papers_first_seen_at"), ["first_seen_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_papers_openalex_id"), ["openalex_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_papers_published_at"), ["published_at"], unique=False)

    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("name_zh", sa.String(length=128), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topics_slug"), ["slug"], unique=True)

    op.create_table(
        "paper_topics",
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("paper_id", "topic_id"),
    )
    op.create_table(
        "researchers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("semantic_scholar_id", sa.String(length=64), nullable=True),
        sa.Column("openalex_id", sa.String(length=64), nullable=True),
        sa.Column("orcid", sa.String(length=32), nullable=True),
        sa.Column("arxiv_author_id", sa.String(length=64), nullable=True),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column("name_zh", sa.String(length=255), nullable=True),
        sa.Column("name_zh_source", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("twitter_handle", sa.String(length=64), nullable=True),
        sa.Column("github_handle", sa.String(length=64), nullable=True),
        sa.Column("zhihu_url", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column("current_affiliation_id", sa.Integer(), nullable=True),
        sa.Column("current_role", sa.String(length=32), nullable=True),
        sa.Column("career_stage_year", sa.Integer(), nullable=True),
        sa.Column("graduation_year_estimate", sa.Integer(), nullable=True),
        sa.Column("advisor_id", sa.Integer(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("bio_zh", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("country_source", sa.String(length=32), nullable=True),
        sa.Column("role_source", sa.String(length=32), nullable=True),
        sa.Column("affiliation_source", sa.String(length=32), nullable=True),
        sa.Column("confidence_level", sa.String(length=16), nullable=False),
        sa.Column("h_index", sa.Integer(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("works_count", sa.Integer(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("projects", sa.JSON(), nullable=True),
        sa.Column("signature_paper_id", sa.Integer(), nullable=True),
        sa.Column("person_score", sa.Float(), nullable=True),
        sa.Column("trajectory_score", sa.Float(), nullable=True),
        sa.Column("investability_score", sa.Float(), nullable=True),
        sa.Column("investability_score_v2", sa.Float(), nullable=True),
        sa.Column("deep_dive_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deep_dive_sources_used", sa.JSON(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["advisor_id"],
            ["researchers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_affiliation_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signature_paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("orcid"),
        sa.UniqueConstraint("semantic_scholar_id"),
    )
    with op.batch_alter_table("researchers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_researchers_name_en"), ["name_en"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_researchers_openalex_id"), ["openalex_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_researchers_slug"), ["slug"], unique=True)

    op.create_table(
        "affiliations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("researcher_id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["researcher_id"],
            ["researchers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("affiliations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_affiliations_institution_id"), ["institution_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_affiliations_researcher_id"), ["researcher_id"], unique=False
        )

    op.create_table(
        "paper_authors",
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("researcher_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_corresponding", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["researcher_id"], ["researchers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("paper_id", "researcher_id"),
    )
    op.create_table(
        "relationships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_researcher_id", sa.Integer(), nullable=False),
        sa.Column("to_researcher_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_researcher_id"],
            ["researchers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_researcher_id"],
            ["researchers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_relationships_from_researcher_id"), ["from_researcher_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_relationships_to_researcher_id"), ["to_researcher_id"], unique=False
        )

    op.create_table(
        "researcher_topics",
        sa.Column("researcher_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["researcher_id"], ["researchers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("researcher_id", "topic_id"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("researcher_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["researcher_id"],
            ["researchers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_signals_occurred_at"), ["occurred_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_signals_researcher_id"), ["researcher_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_signals_type"), ["type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signals_type"))
        batch_op.drop_index(batch_op.f("ix_signals_researcher_id"))
        batch_op.drop_index(batch_op.f("ix_signals_occurred_at"))

    op.drop_table("signals")
    op.drop_table("researcher_topics")
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relationships_to_researcher_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_from_researcher_id"))

    op.drop_table("relationships")
    op.drop_table("paper_authors")
    with op.batch_alter_table("affiliations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_affiliations_researcher_id"))
        batch_op.drop_index(batch_op.f("ix_affiliations_institution_id"))

    op.drop_table("affiliations")
    with op.batch_alter_table("researchers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_researchers_slug"))
        batch_op.drop_index(batch_op.f("ix_researchers_openalex_id"))
        batch_op.drop_index(batch_op.f("ix_researchers_name_en"))

    op.drop_table("researchers")
    op.drop_table("paper_topics")
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topics_slug"))

    op.drop_table("topics")
    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_papers_published_at"))
        batch_op.drop_index(batch_op.f("ix_papers_openalex_id"))
        batch_op.drop_index(batch_op.f("ix_papers_first_seen_at"))
        batch_op.drop_index(batch_op.f("ix_papers_arxiv_id"))

    op.drop_table("papers")
    with op.batch_alter_table("institutions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_institutions_openalex_id"))
        batch_op.drop_index(batch_op.f("ix_institutions_name"))

    op.drop_table("institutions")
    with op.batch_alter_table("deep_dive_quota", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deep_dive_quota_ip_address"))
        batch_op.drop_index(batch_op.f("ix_deep_dive_quota_day"))

    op.drop_table("deep_dive_quota")
    with op.batch_alter_table("deep_dive_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deep_dive_jobs_state"))
        batch_op.drop_index(batch_op.f("ix_deep_dive_jobs_slug"))

    op.drop_table("deep_dive_jobs")
    with op.batch_alter_table("daily_briefs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_briefs_brief_date"))

    op.drop_table("daily_briefs")
    # ### end Alembic commands ###
