"""metric snapshots

Revision ID: 995c00c9c02d
Revises: a1b2c3d4e5f6
Create Date: 2026-06-11 14:20:03.568049

Adds the `metric_snapshots` table — one row per researcher per day,
written by the daily pipeline's snapshot step (only researchers with
investability_score_v2 > 0). Backs the trend sparklines on the profile
page via `GET /researchers/{slug}/history`.

Schema-only migration: no data backfill. History accrues from the first
daily run after deploy.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "995c00c9c02d"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("researcher_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_date", sa.String(length=10), nullable=False),
        sa.Column("h_index", sa.Integer(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("works_count", sa.Integer(), nullable=True),
        sa.Column("investability_v2", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["researcher_id"],
            ["researchers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("metric_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_metric_snapshots_researcher_id"), ["researcher_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_metric_snapshots_snapshot_date"), ["snapshot_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metric_snapshots_snapshot_date"))
        batch_op.drop_index(batch_op.f("ix_metric_snapshots_researcher_id"))

    op.drop_table("metric_snapshots")
    # ### end Alembic commands ###
